# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

branches:
  only:
  - develop
  - master

env:
  global:
  - MAKEFLAGS="-j 2"

before_install:
  - cd mmb

after_success:
  - Rscript -e 'covr::codecov()'
