# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

branches:
  only:
  - master

env:
  global:
  - MAKEFLAGS="-j 2"
  - IS_BUILD_COMMAND=TRUE

before_install:
  - cd pkg/mmb

after_success:
  - Rscript -e 'covr::codecov()'
