comment: false

fixes:
  - "::pkg/mmb/" # move root, "/" => "pkg/mmb/"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
